# Generated by Django 5.0.2 on 2024-03-01 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('userRoll', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articls',
            fields=[
                ('articlsId', models.IntegerField(primary_key=True, serialize=False)),
                ('articlsTitle', models.CharField(max_length=150)),
                ('articlsContent', models.TextField()),
                ('articlsDate', models.DateTimeField()),
                ('publisherId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentId', models.IntegerField(primary_key=True, serialize=False)),
                ('commentContent', models.TextField()),
                ('commentDate', models.DateTimeField()),
                ('articalId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articls')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('PublisherId', models.IntegerField(primary_key=True, serialize=False)),
                ('userNmae', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('userRoll', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('articlsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articls')),
            ],
        ),
    ]
