# Generated by Django 5.0.2 on 2024-04-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articlsContent',
            new_name='articleContent',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='articlsDate',
            new_name='articleDate',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='articlsTitle',
            new_name='articleTitle',
        ),
    ]
