# Generated by Django 5.0.2 on 2024-03-18 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articlsDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 22, 42, 592727)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 11, 22, 42, 592727)),
        ),
    ]
