# Generated by Django 5.0.2 on 2024-04-11 10:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_articlsdate_alter_comment_commentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='userNmae',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='userRoll',
        ),
        migrations.AddField(
            model_name='publisher',
            name='city',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='country',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='phone',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='publisherName',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='articlsDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 16, 5, 20, 342814)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 16, 5, 20, 342814)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_roll',
            field=models.CharField(choices=[('user', 'user'), ('publisher', 'publisher')], default='user', max_length=15),
        ),
    ]
