# Generated by Django 5.0.2 on 2024-04-11 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_publisher_email_remove_publisher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='articlsDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 16, 11, 24, 718567)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 16, 11, 24, 719600)),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisherName',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
